# .streamlit/secrets.toml
[connections.postgresql]
dialect = "postgresql"
host = "ep-tiny-violet-atfv81pa-pooler.c-9.us-east-1.aws.neon.tech"
database = "neondb"
username = "neondb_owner"
password = "npg_uAOK2mTgc8pU"
port = 5432
